### ISSUE TITLE
Unresolved dependency to Schyntax 1.0.1.32

### ISSUE THREAD

**Issue by Spiralis** [schyntax/cs-schtick#1]
When I am using the latest version (1.0.4) I am getting an error saying that it requires Schyntax  version 1.0.1.32. 

Now, the dependencies in the Schtick.nuspec says that `<dependency id="Schyntax" version="1.0.1"/>` and in NuGet that seems to be translated to >= 1.0.1. When installing this it fetches the latest Schyntax (1.0.3), and building is fine. When running the application things fail with an exception as it tries to find Schyntax-1.0.1.32 

This seems to me like the assemblyinfo.cs file contains to "specific" version specs. For our products we on purpose populate the AssemblyVersion tag with only the Major version-number. This is because internally the .Net applications binds to the specific AssemblyVersion of the dependencies used during compilation. 

So, in the case with Schtick, when it was built and when the package was created it seems that it was bound to the 1.0.1.32 assembly-version. If you use semantic versioning (as we do) I suggest you change this to contain only the majorversion. I think this is a far more flexible solution than having to add binding-configuration (which is also an option of course, but very annoying...).

Here is a sample from one of my assemblyinfo.cs files:

```
[assembly: System.Reflection.AssemblyVersion("1")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.1.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("1.0.1-Alpha-151111145421ro")]
```

**Comment by bretcope** [comment]
I hadn't run into this problem before. That seems like a reasonable solution. I'll look into it.

**Comment by Spiralis** [comment]
:+1:

**Comment by bretcope** [comment]
I've looked into the various options, and decided to go with what you suggested. Schyntax/Schtick are updated.
